### ISSUE TITLE
ViewPagerAndroid has been removed from React Native

### ISSUE THREAD

**Issue by MTayyabMehar** [rip3rs/react-native-carousel#1]
I am getting the following error please update it as soon as possible.
ViewPagerAndroid has been removed from React Native. It can now be installed and imported from 'react-native-viewpager" insted of 'react-native'.

**Comment by rip3rs** [comment]
@MTayyabMehar I have updated, thank you for the info.

I have updated as well the package.json, alas at this moment I am not able to test if anything will break.

If it does, please tell me and I will revert it.
